title: Nicolas Lebovitz # your name (or website title) here
logo: "/images/nico.jpeg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Accomplished naval officer seeking new opportunities in Data Science and Technical Leadership.
  <br><br>
  <a href="https://www.linkedin.com/in/nico-lebovitz">View My LinkedIn Profile</a> 
theme: jekyll-theme-minimal
#google_analytics: UA-000000-0 # your Google Analytics tracking ID here
